api = "0.10"
WithWindowsBuild = false
WithLinuxBuild = false

[buildpack]
id = "porter-dev/unrtf"
version = "0.0.3"

[[targets]]
os = "linux"
arch = "amd64"

[[targets.distributions]]
name = "ubuntu"
versions = ["20.04", "22.04"]

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "heroku-20"

[[stacks]]
id = "heroku-22"
